"""
PatternAnalyzerAgent — Chart Pattern Recognition Expert
Agent Phân Tích Mẫu Giá — Chuyên Gia Nhận Dạng Mẫu Biểu Đồ

Responsibilities / Trách nhiệm:
  - Load the chart PNG just generated by VisualizerAgent
  - Compare against all images in ./patterns/ folder
  - Use SSIM + pHash + CLIP for multi-method scoring
  - Detect if price is near key S/R levels
  - Return top 3 pattern matches with confidence %
"""

from __future__ import annotations

from typing import Any, Dict

from crewai import Agent, Task
from utils.llm_factory import get_llm

from tools.pattern_tools import PatternMatchTool, SupportResistanceTool


def create_pattern_analyzer_agent(config: Dict[str, Any]) -> Agent:
    """
    Build the PatternAnalyzerAgent.
    Xây dựng PatternAnalyzerAgent.
    """
    llm = get_llm(config)

    return Agent(
        role="Chart Pattern Recognition Expert",
        goal=(
            "Analyse the latest chart image against a library of known price action patterns "
            "(Hammer, Engulfing, Head & Shoulders, Double Top/Bottom, Triangle, Flag, etc.) "
            "using computer vision. Also identify if the current price is at a key support or "
            "resistance level. Return the top 3 matching patterns with confidence percentages."
        ),
        backstory=(
            "You are a specialist in computer vision applied to financial chart analysis. "
            "You combine classical CV techniques (SSIM, perceptual hashing) with modern deep "
            "learning (CLIP embeddings) to achieve robust pattern recognition even with noisy charts. "
            "You have trained on thousands of manually annotated forex chart patterns. "
            "Bạn là chuyên gia về thị giác máy tính ứng dụng trong phân tích biểu đồ tài chính, "
            "kết hợp các kỹ thuật CV cổ điển với học sâu hiện đại."
        ),
        tools=[
            PatternMatchTool(),
            SupportResistanceTool(),
        ],
        llm=llm,
        verbose=config.get("logging", {}).get("verbose", True),
        allow_delegation=False,
        max_iter=5,
    )


def create_pattern_analysis_task(
    agent: Agent,
    context: Dict[str, Any],
    config: Dict[str, Any],
) -> Task:
    """
    Create a pattern recognition task.
    Tạo nhiệm vụ nhận dạng mẫu giá.
    """
    symbol = context["symbol"]
    timeframe = context["timeframe"]
    charts_dir = config.get("charts", {}).get("folder", "./charts")
    patterns_dir = config.get("patterns", {}).get("folder", "./patterns")
    top_n = config.get("patterns", {}).get("top_matches", 3)
    min_conf = config.get("patterns", {}).get("min_confidence", 0.25)
    lookback = config.get("trading", {}).get("sr_lookback", 100)
    tol_pips = config.get("trading", {}).get("sr_tolerance_pips", 10.0)

    chart_path = f"{charts_dir}/current_{symbol}_{timeframe}.png"

    return Task(
        description=(
            f"Perform pattern recognition on the {symbol} {timeframe} chart.\n\n"
            f"Steps:\n"
            f"1. Use pattern_match with:\n"
            f"   - chart_path='{chart_path}'\n"
            f"   - patterns_dir='{patterns_dir}'\n"
            f"   - top_n={top_n}\n"
            f"   - min_confidence={min_conf}\n"
            f"   This will use SSIM + perceptual hashing + CLIP to find matching patterns.\n\n"
            f"2. Use support_resistance with symbol='{symbol}', timeframe='{timeframe}', "
            f"lookback={lookback}, tolerance_pips={tol_pips} to identify key price levels.\n\n"
            f"3. Combine the results: which patterns were found, their confidence, and whether "
            f"the current price is at a significant S/R level.\n\n"
            f"4. Return a comprehensive JSON with: top_patterns (list of {{name, confidence}}), "
            f"best_pattern, best_confidence, sr_context (at_support/at_resistance/mid_range), "
            f"current_price, key_levels."
        ),
        expected_output=(
            "A JSON string with: best_pattern (string), best_confidence (float 0-100), "
            "top_patterns (list), sr_context (string), current_price (float), "
            "resistance_levels (list), support_levels (list), "
            "trade_bias ('bullish'/'bearish'/'neutral' based on pattern + S/R)."
        ),
        agent=agent,
    )
